### PR TITLE
Fix unistd.h check.

### PR DESCRIPTION
**Pull request by vinsonlee**
This patch fixes this compiler error.

/usr/include/dispatch/dispatch.h:38:45: error: expected value in expression
                                            ^

Fixes: 8af68ef3e4bb ("fix invalid use of config defines in API/SPI headers")
Signed-off-by: Vinson Lee <vlee@freedesktop.org>

### CODE REVIEW

**Comment by MadCoder** [comment]
fixes which compilation error in which environment exactly?

**Comment by vinsonlee** [comment]
piglit (https://cgit.freedesktop.org/piglit) fails to build on macOS High Sierra 10.13.2 with clang-900.0.39.2. 

In file included from piglit/tests/util/piglit-util-cl.c:26:
In file included from piglit/tests/util/piglit-util-cl.h:29:
In file included from piglit/tests/util/piglit-util-cl-enum.h:34:
In file included from /System/Library/Frameworks/OpenCL.framework/Headers/opencl.h:16:
In file included from /System/Library/Frameworks/OpenCL.framework/Headers/gcl.h:23:
/usr/include/dispatch/dispatch.h:38:45: error: expected value in expression
#if !defined(HAVE_UNISTD_H) || HAVE_UNISTD_H
                                            ^

**Comment by MadCoder** [comment]
this is a bug in piglit, it defines HAVE_UNISTD_H with #cmakedefine instead of #cmakedefine01:

tests/util/config.h.in:#cmakedefine HAVE_UNISTD_H.
arguably using HAVE_UNISTD_H in `<dispatch/dispatch.h>` is problematic on its own, but we can't rely on compilers supporting `__has_include` for API headers.
